### ISSUE TITLE
No longer runs after 1-16 update

### ISSUE THREAD

**Issue by cyphr3x** [ChristopherHX/mcpelauncher-manifest#111]
Logs
linker: ... dlclose: calling destructors for "/Users/ted/Library/Application Support/mcpelauncher/versions/1.16.0.2/lib/x86_64/libc++_shared.so"@0x10c398a90 ... 
linker: ... dlclose: calling destructors for "/Users/ted/Library/Application Support/mcpelauncher/versions/1.16.0.2/lib/x86_64/libc++_shared.so"@0x10c398a90 ... done
linker: ... dlclose: unloading "/Users/ted/Library/Application Support/mcpelauncher/versions/1.16.0.2/lib/x86_64/libminecraftpe.so"@0x10c398810 ...
linker: ... dlclose: unloading "/Users/ted/Library/Application Support/mcpelauncher/versions/1.16.0.2/lib/x86_64/libc++_shared.so"@0x10c398a90 ...
linker: ... dlclose: unload_si was not linked - not unloading external references ...
linker: ... dlopen failed: cannot locate symbol "_ZN4FMOD14ChannelControl9getVolumeEPf" referenced by "/Users/ted/Library/Application Support/mcpelauncher/versions/1.16.0.2/lib/x86_64/libminecraftpe.so"...

Process exited with unexpected exit code: 15

**Comment by ChristopherHX** [comment]
Please provide your current Launcher Version (settings check for updates)
I assume it is outdated, because this bug is fixed since Tuesday's evening update to ng for macOS 10.14, 10.15.
In case you want to reinstall it manually fixed in
https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/ng.dmg/Minecraft_Bedrock_Launcher_0.0.168_macOS_10.12.0.dmg
You should be able to update via the launcher


Your log is stripped,
It is not the best idea to crop the crash log, because it reduces it's information.
e.g. the full log would tell me the internal gamelauncher version

**Comment by cyphr3x** [comment]
The launcher you posted here works, thanks!
