### ISSUE TITLE
Google OAuth browser not safe

### ISSUE THREAD

**Issue by ekifox** [ChristopherHX/mcpelauncher-manifest#114]
![image](https://user-images.githubusercontent.com/1989823/86421744-c95af180-bce3-11ea-82bc-4e5ecdb1ba55.png)

**Comment by ChristopherHX** [comment]
There was a bad launcher version for Catalina yesterday
Please install this (only macOS 10.15)
https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/ng.dmg/Minecraft_Bedrock_Launcher_0.0.168_macOS_10.12.0.dmg

Or visit stable Releases again https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage


This bug should be fixed since a half year, are you shure it wasn't the wiki release

**Comment by ChristopherHX** [comment]
No response, please reopen if you answer __all__ my questions
