### ISSUE TITLE
Only login working in network

### ISSUE THREAD

**Issue by soshimee** [ChristopherHX/mcpelauncher-manifest#143]
Nothing that uses internet work except XBOX login, it used to work at fresh install, but it's not working anymore.
Also it confuses it with privacy settings.

**Comment by ChristopherHX** [comment]
> Also it confuses it with privacy settings.
This happens if sign in fails, due to timeout

https://github.com/ChristopherHX/mcpelauncher-manifest/issues/42
starting msa-daemon prior starting the game is a workaround against this timeout and "privacy settings" error message of the game.

_This error is gone with Minecraft 1.16.20+_, only in preview update

**Comment by soshimee** [comment]
1.16.20+ doesn't work, currently using 1.16.10.
Also, the workaround doesn't affect anything for me.

**Comment by soshimee** [comment]
Now that I'm using 1.16.100, it is same as before, but login less glitchy.

**Comment by ChristopherHX** [comment]
I assume this can be closed.
