### ISSUE TITLE
Render Distance

### ISSUE THREAD

**Issue by null2264** [ChristopherHX/mcpelauncher-manifest#15]
This issue was happens on 1.13.x and already reported to issue tab, so i just have to wait till 1.14.x come out. But when it released it get worse, on 1.13 i can set it to 8 chunks but now it reduced to 6 chunks.
I tried to manually set it from option file but it didn't do anything, it's fine to play on low render distance but its still bothering me.

**Comment by ChristopherHX** [comment]
Are you shure you cannot set custom renderdistance in `~/.local/share/mcpelauncher/games/com.mojang/minecraftpe/option.txt` for example I even be able to enter gfx_viewdistance:800 <=> 50 chunks on my Intel UHD 8th gen it isn't fast, but the game accept it, the path in the mrarm launcher maybe currently different
800: 50
400: 25
...

**Comment by null2264** [comment]
Yes, i tried multiple times with different value its still stays 6 chunks, even if I straight up load a world or when i check the setting first (Just incase that might reset the render distance to 6 chunks).

**Comment by ChristopherHX** [comment]
Why should the Game resetting to 6 chunks only on your PC, but not on other PC's editing.
Please update my fork frequently (Rolling Release, but slower than archlinux),
I can't reproduce the bahavior of resetting to 6 chunks render distance.
Does Minecraft actually modify the config that you are editing? (maybe you changed an unused config.txt, compare the edited with the one after start)
Only rounding down to next chunk distance is noticed by me. (`gfx_viewdistance:300` changed to `gfx_viewdistance:288`
Or you need to wait for the mrarm launcher to update, because I not think my fork get merged at all.

**Comment by null2264** [comment]
I will try to find what I may do wrong, the save directory kinda confusing for me (some folder have similar name) I might mistaken something. For now I will keep updating your fork while waiting for the MrArm's to be updated.

**Comment by null2264** [comment]
Update : SOLVED! I mistaken 2 folder that both named "minecraftpe" both have option.txt, should've mess with this thing when i focused. Thanks for the replies btw...

**Comment by Mhowser** [comment]
Can you tell us the absolute path to the right config file?

**Comment by null2264** [comment]
Its on `.local/share/mcpelauncher/games/com.mojang/minecraftpe/option.txt`

**Comment by Mhowser** [comment]
Thanks!

**Comment by michael-ts** [comment]
I'm not sure why, but on my machine I can't seem to get the render distance to go higher than 32 chunks.  No matter how much higher I set it than this, I still can only see 256 blocks in any given direction.

I edited options.txt and found that gfx_viewdistance was set to 512, so I doubled it to 1024 and restarted, with no effect.  I also bumped vr_renderdistance from 1024 to 2048 but it got reduced to 1536.

If I'm understanding these variables correctlly, a gfx_viewdistance of 512 means that I should be able to see 256 blocks in any direction and is equal to a render distance of 512 / 8 = 32.  So doubling it should allow me to see 512 blocks ahead when I set render distance to 64, but I still can only see 256 blocks.  The same is true if I set the render distance to 80. It does take quite a bit longer to load the map, and I'm getting the "waiting" animation at times, but I'm only using a small fraction of my CPU / GPU / RAM / GPU RAM.

It also won't let me enable ray tracing despite the fact that I've got support for it on my GPU.

Is there some hard-coded limitation here?  Is it just not able to take advantage of my hardware due to the Android translation layer or something?
