### ISSUE TITLE
Launcher Crashed

### ISSUE THREAD

**Issue by iFlank** [ChristopherHX/mcpelauncher-manifest#154]
Did older Launcher Versions work on this PC?
```
17:30:12 Trace [HybrisUtils] Loaded OS library libz.dylib
17:30:12 Trace [HybrisUtils] Loaded OS library libm.dylib
17:30:13 Trace [HybrisUtils] Loaded OS library /private/var/folders/22/8fwyrx054f938prfsxx924rm0000gn/T/AppTranslocation/AD4E8526-9441-42FF-8D8E-AA904674A75E/d/Minecraft Bedrock.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
Signal 11 received
Backtrace elements: 8
#0 0   mcpelauncher-client                 0x000000010338cf92 _ZN12CrashHandler12handleSignalEiPv + 226
#1 1   libsystem_platform.dylib            0x00007fff6bb035fd _sigtramp + 29
#2 2   mcpelauncher-client                 0x000000010364d000 _ZNSt3__1L19piecewise_constructE + 300868
#3 3   mcpelauncher-client                 0x000000010336cbcd _ZN11HookManager7LibInfoC1EPv + 29
#4 4   mcpelauncher-client                 0x000000010336d26a _ZN11HookManager10addLibraryEPv + 90
#5 5   mcpelauncher-client                 0x0000000103067633 main + 7571
#6 6   libdyld.dylib                       0x00007fff6b90acc9 start + 1
#7 7   ???                                 0x0000000000000007 0x0 + 7
Dumping stack...

Process exited with unexpected exit code: 6

```
# Disclaimer
If you don't answer these questions your issue will be closed

**Comment by ChristopherHX** [comment]
- please install the latest update
- You will have to copy the launcher to an writtable location like Applications to opt in to the updater
- Otherwise you should have got an popup after start.
- Here a link to dmg for high sierra incase the updater won't work, but shouln't be required
https://github.com/ChristopherHX/osx-packaging-scripts/releases/download/ng.dmg/Minecraft_Bedrock_Launcher_0.1.b1-macOS-x86_64-0.2.252_macOS_10.13.0.dmg

- If you still get a crash, try deleting the specfic gameversion inside the launcher and download it fresh again.

**Comment by ChristopherHX** [comment]
I heard of a potenially tampered Launcher from mediafire

You find offical releases from me on github (https://github.com/ChristopherHX/osx-packaging-scripts/releases/tag/ng.dmg).
They are still unsigned, but it seems to be reasonable to increase secureity.
