### ISSUE TITLE
Why does the launcher use ng?

### ISSUE THREAD

**Issue by nazthelizard122** [ChristopherHX/mcpelauncher-manifest#196]
So basically everyone who has used this launcher knows about ng and it's instability so why are we using it when there's others?

**Comment by ChristopherHX** [comment]
ng is better, a few arguments

- Demand to have it ob Catalina and later, apple's 32bit removal
- Demand to use xboxlive after 1.16.10
- sound after 1.16.10 (macOS)
- 64bit Minecraft
   - arm64/linux
   - amd64/linux
   - amd64/macos
   - arm64/macos, wip
- No need to maintain a seperate launcher based on obsolete source code

Otherwise it would be still possible to update.

ng is a rewrite of the old launcher, and the merge of my fork.

**Comment by ChristopherHX** [comment]
> when there's others?

Which others?, As far as I know only the minecraft-linux launcher exists.
I done some reverse engineering myself to remove a lot of dependencies to implentation details of Minecraft Pe / Bedrock used previously.
-> my fork was the result

You can also help improving the launcher and fix the instability!

**Comment by nazthelizard122** [comment]
> Which others?, As far as I know only the minecraft-linux launcher exists.

I figured there would be other launchers for Linux 

> You can also help improving the launcher and fix the instability!

I would if I knew how to code best I know is how to navigate a file system using terminal

**Comment by nazthelizard122** [comment]
1.16.100.60 is best for joining servers, crashes are rare and you can view memory usage ingame
