### ISSUE TITLE
Mouse Pointer Is Not Captured by Window

### ISSUE THREAD

**Issue by Kas-tle** [ChristopherHX/mcpelauncher-manifest#202]
When playing the 210 betas, I have noticed that the windows does not seem to capture my mouse pointer on my system.

Reproduction:
- Launch with the given parameters described below (MacOS Mojave 10.14.6, Bedrock Version 1.16.210.50-1.16.210.58, Launcher Version0.1.b5-macOS-x86_64-0.2.275 build 275)
- Generate a clean world
- Observe that the game fails to capture the mouse cursor

System Information:
System OS: MacOS Mojave 10.14.6
Launcher Version: 0.1.b5-macOS-x86_64-0.2.275 (build 275)
Bedrock Version: 1.16.210.50-1.16.210.58

I have attached the launcher log from between starting to joining a world if that could be of use. Please let me know if there is anything else I can add to help.

[launcher.log](https://github.com/ChristopherHX/mcpelauncher-manifest/files/5935493/launcher.log)

**Comment by ChristopherHX** [comment]
Your problem is in the log, that was a crash in versions before 2021.1:
`13:46:01 Error [CorePatches] Failed to patch vtable _ZTV21AppPlatform_android23 not found`
I literally just fixed the crash not anything else yet.
I'm more concerned about the fact that the textures of blocks have a weird offset on my pc, while playing the beta with full keyboard gameplay.

Thats why you shouldn't play betas , if you aren't a launcher developer or want to become one it is in the dev tab anyway. You can use any other input methods just fine.

**Comment by Kas-tle** [comment]
Realized this is now no longer relevant. Apologies for keeping it open.
