### ISSUE TITLE
build_appimage.sh from ChristopherHX/linux-packaging-scripts does not create a 1.16.220-compatible launcher.

### ISSUE THREAD

**Issue by TheSonicMaster** [ChristopherHX/mcpelauncher-manifest#245]
Hello, I have run into something very strange, and would like some extra information on how you created your 1.16.220-compatible AppImage.

I used the build_appimage.sh script from https://github.com/ChristopherHX/linux-packaging-scripts, by using the following steps:
```
git clone https://github.com/ChristopherHX/linux-packaging-scripts.git
cd linux-packaging-scripts
CC=clang CXX=clang++ ./build_appimage.sh
```
And this script does successfully create a launcher AppImage, however the launcher created does not support 1.16.220. Attempts to open 1.16.220 crash on startup just like they did with the older AppImage.

My question is, how did you make your newest AppImage support 1.16.220? What did you do that was different to what I did? Is there something I am missing?

Thank you in advance.

**Comment by ChristopherHX** [comment]
# First of all, I dislike your posts / repositories / aur which promotes piracy.

For example you repo which mentions my legal work together with illegal content.
I added the license check only, because people like you **abused** my prebuilds for **piracy** and published links to my work. Now you promote AUR / .deb packages with 'fixed license error' this doesn't feel good either, but I guess I cannot prevent it for now.

> My question is, how did you make your newest AppImage support 1.16.220? What did you do that was different to what I did?

I don't run the script on my (local) machine, only via github actions using github-hosted runners. Anything else is a leftover from the past.

You need to run this file https://github.com/ChristopherHX/linux-packaging-scripts/blob/main/.github/workflows/main.yml to get it.
GitHub Actions log:
https://github.com/ChristopherHX/linux-packaging-scripts/actions/runs/746010647
