### ISSUE TITLE
Can't import skin.

### ISSUE THREAD

**Issue by derspyy** [ChristopherHX/mcpelauncher-manifest#83]
no windows opens up to choose skin

**Comment by ChristopherHX** [comment]
> no windows opens up to choose skin

I'm not aware that this is not working with the stable launcher https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage

**I guess you downloaded the unfinished Prerelease of ng**
https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/ng.appimage
instead of the [stable one](https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage)
Please install the stable one, logout from google in setting, login again in the stable and redownload the Game (delete it in settings, because it may be x86_64 which isn't working in stable)

Should I hide it, or how should I label it to minimize confusion?, A bold headline and scroll down isn't enough

**Comment by ChristopherHX** [comment]
Copied over from master, should now work on ng
