### ISSUE TITLE
No Sound on Stable Release Launcher with Minecraft 1.14.60.5

### ISSUE THREAD

**Issue by TechnologyMan101** [ChristopherHX/mcpelauncher-manifest#88]
Cannot get sound on Stable Launcher with Minecraft 1.14.60.5.

Stable AppImage Release on Pop!_OS 20.04 LTS with all dependencies satisfied.

**Comment by ChristopherHX** [comment]
Idk, you are on your own with your gnu/linux distro
Checkout the wiki of minecraft-linux
https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html#no-audio
**There are far to many gnu/linux distros out there**
The ng only worked, because it doesn't depend on not installed 32bit audio libs (64bit deps are on most desktop distros preinstalled)

**Comment by TechnologyMan101** [comment]
I followed your link and used the Ubuntu instructions to fix the problem. Maybe you should include **libpulse0:i386** in the Debian instructions.

**Comment by ChristopherHX** [comment]
Release Page updated
